### ISSUE TITLE
使用下面的代码，可以把编译器降低到c++11

### ISSUE THREAD

**Issue by zhaoyaogit** [an-tao/trantor#154]
//from https://github.com/zhaoyaogit/rpclib
#ifndef MAKE_UNIQUE_HPP
#define MAKE_UNIQUE_HPP

#include <memory>

namespace std {
// Default behaviour is to assume C++11, overriding RPCLIB_CXX_STANDARD can use
// newer standards:
#if RPCLIB_CXX_STANDARD >= 14

using std::make_unique;

#else

template<typename T, typename... Ts>
std::unique_ptr<T> make_unique(Ts&&... params)
{
   return std::unique_ptr<T>(new T(std::forward<Ts>(params)...));
}

#endif

}

#endif /* end of include guard: MAKE_UNIQUE_HPP */

**Comment by an-tao** [comment]
可能还不行，工程里还用了其它c++14以后的特性，比如lambda捕获列表里的move

**Comment by zhaoyaogit** [comment]
可是经过我编译测试：
Redhat 7.2.1511       gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
在以上环境下所需要std::make_unique的头文件：TcpConnectionImpl.h增加头文件引用#include "unique.h"
编译通过。正常生成静态库.a文件。

**Comment by zhaoyaogit** [comment]
对了：BufferNode() =default ;改为BufferNode();
就改了这两处，编译过去的。

**Comment by an-tao** [comment]
哦哦，trantor会好些，我以为drogon呢
