### ISSUE TITLE
Cannot send email using SMTPMail plugin

### ISSUE THREAD

**Issue by shivshankardayal** [an-tao/trantor#179]
Trantor gives following errors:

20210913 13:58:12.810493 UTC 57380 ERROR Domain validation failed - TcpConnectionImpl.cc:1677
20210913 13:58:12.810536 UTC 57380 ERROR SSL certificate validation failed. - TcpConnectionImpl.cc:1696

I am using letsencrypt certificates and can send email using mail command.

**Comment by an-tao** [comment]
which plugin do you use? Is it https://github.com/an-tao/SMTPMail-drogon?

**Comment by shivshankardayal** [comment]
I am using https://github.com/ihmc3jn09hk/SMTPMail-drogon

**Comment by an-tao** [comment]
I made some changes of it, you could try the version of mine.

**Comment by shivshankardayal** [comment]
Okay I will try it tomorrow and let you know.

**Comment by shivshankardayal** [comment]
No even your repository does not work. The problem is not with SMTPMail but trantor.  https://github.com/an-tao/SMTPMail-drogon/blob/master/SMTPMail.cc#L156 is where the problem starts and gives the two messages in log. I tested my mail server with Python smtplib and it is working fine.

**Comment by shivshankardayal** [comment]
Consider following code
```c++
nline std::string certNameToRegex(const std::string &certName)
{
    std::string result;
    result.reserve(certName.size() + 11);

    bool isStar = false;
    bool isLeadingStar = true;
    for (char ch : certName)
    {
        if (isStar == false)
        {
            if (ch == '*')
                isStar = true;
            else if (ch == '.')
            {
                result += "\\.";
                isLeadingStar = false;
            }
            else
            {
                result.push_back(ch);
                isLeadingStar = false;
            }
        }
        else
        {
            if (ch == '.' && isLeadingStar)
                result += "([^.]*\\.|)?";
            else
                result += std::string("[^.]*") + ch;
            isStar = false;
        }
    }
    assert(isStar == false);
    return result;
}
```
If the CN in certificate is *.somesiite.com then regex would be `([^.]*\\.|)?` which will not match with CN in verification.

**Comment by marty1885** [comment]
@shivshankardayal May you elaborate a bit more?

I ran some tests and it does match. For example `certNameToRegex("*.example.com")` generates `([^.]*\.|)?example\.com`. Which does match all single level subdomains of example.com

![image](https://user-images.githubusercontent.com/8792393/148402150-6572024d-c304-4788-94b3-cd64bac86ec1.png)

**Comment by shivshankardayal** [comment]
I see. The problem is that I am trying to an email through my SMTP server which has wildcard ssl certificate. But trantor complains that "domain validation failed". As I have said above Python SMTPlib can successfully send email using the same server. It has been so many months but I still cannot fix it.

**Comment by marty1885** [comment]
May you share which server are you sending to? Maybe it's using a multi-level wildcard? I can patch that.

**Comment by shivshankardayal** [comment]
It is `ashtavakra.org`

**Comment by shivshankardayal** [comment]
@marty1885 Did you figure out the problem?

**Comment by marty1885** [comment]
@shivshankardayal Sorry, I got caught on debugging other projects. I'll debug this tomorrow and get back to you in 1 or 2 days. Please poke me if I forgot or get sidetracked.

**Comment by marty1885** [comment]
@shivshankardayal Hmm... I am not sure what's the case for the mail server. I can get HTTP client to connect correctly. Their main site also uses the same *.ashtavakra.org certificate:

![image](https://user-images.githubusercontent.com/8792393/148767698-65afbad9-84db-4e5b-891f-68530604e735.png)

I'm also able to verify Drogon is doing verification correctly. We do read the wildcard cert and we do generate the correct regex.

```
20220110 12:52:17.443890 UTC 8133 TRACE [validatePeerCertificate] Validating peer cerificate - TcpConnectionImpl.cc:1720
20220110 12:52:17.443908 UTC 8133 DEBUG [verifyCommonName] Cert CommonName: *.ashtavakra.org - TcpConnectionImpl.cc:137
20220110 12:52:17.443925 UTC 8133 DEBUG [verifyCommonName] Compare against hostname: ashtavakra.org - TcpConnectionImpl.cc:138
20220110 12:52:17.443931 UTC 8133 DEBUG [verifyName] *.ashtavakra.org => ([^.]*\.|)?ashtavakra\.org - TcpConnectionImpl.cc:119
20220110 12:52:17.444388 UTC 8133 TRACE [operator()] Connection established! - HttpClientImpl.cc:63
20220110 12:52:17.444406 UTC 8133 TRACE [sendReq] Send request:GET / HTTP/1.1
user-agent: DrogonClient
host: ashtavakra.org
connection: Keep-Alive

 - HttpClientImpl.cc:479
```

May you check that both your Drogon and Trantor (in drogon/trantor) are up to date? And apply this patch to dump the certificate and verification info.

```diff
diff --git a/trantor/net/inner/TcpConnectionImpl.cc b/trantor/net/inner/TcpConnectionImpl.cc
index 2f11e45..5a6df2e 100644
--- a/trantor/net/inner/TcpConnectionImpl.cc
+++ b/trantor/net/inner/TcpConnectionImpl.cc
@@ -116,6 +116,7 @@ inline std::string certNameToRegex(const std::string &certName)
 
 inline bool verifyName(const std::string &certName, const std::string &hostname)
 {
+    LOG_DEBUG << certName << " => " << certNameToRegex(certName);
     std::regex re(certNameToRegex(certName));
     return std::regex_match(hostname, re);
 }
@@ -133,6 +134,8 @@ inline bool verifyCommonName(X509 *cert, const std::string &hostname)
                                                 (int)name.size());
         if (length == -1)
             return false;
+        LOG_DEBUG << "Cert CommonName: " << std::string(name.begin(), name.begin() + length);
+        LOG_DEBUG << "Compare against hostname: " << hostname;
 
         return verifyName(std::string(name.begin(), name.begin() + length),
                           hostname);
@@ -166,9 +169,11 @@ inline bool verifyAltName(X509 *cert, const std::string &hostname)
             auto name = (const char *)ASN1_STRING_data(val->d.ia5);
 #endif
             auto name_len = (size_t)ASN1_STRING_length(val->d.ia5);
+            LOG_DEBUG << "Cert AltName: " << std::string(name, name + name_len);
             good = verifyName(std::string(name, name + name_len), hostname);
         }
     }
+    LOG_DEBUG << "Compare against hostname: " << hostname;
 
     GENERAL_NAMES_free((STACK_OF(GENERAL_NAME) *)altNames);
     return good;
```
My best guess is that either they misconfigured their mail server or you are using a very old build of trantor. The verification code wasn't complying with RFC for a very short period. But we have patched it a long time ago.

![image](https://user-images.githubusercontent.com/8792393/148769690-e8f8910e-af1d-48e2-ab5d-39d31835ef69.png)

**Comment by shivshankardayal** [comment]
@marty1885 I will try again tomorrow and also try with Python SMTP lib with same server settings.

**Comment by shivshankardayal** [comment]
it is quite strange that it does not get hostname.

```
20220114 21:33:40.464702 UTC 10532 DEBUG [verifyCommonName] Cert CommonName: *.ashtavakra.org - TcpConnectionImpl.cc:137
20220114 21:33:40.464753 UTC 10532 DEBUG [verifyCommonName] Compare against hostname:  - TcpConnectionImpl.cc:138
20220114 21:33:40.464764 UTC 10532 DEBUG [verifyName] *.ashtavakra.org => ([^.]*\.|)?ashtavakra\.org - TcpConnectionImpl.cc:119
20220114 21:33:40.465281 UTC 10532 DEBUG [verifyAltName] Cert AltName: *.ashtavakra.org - TcpConnectionImpl.cc:171
20220114 21:33:40.465293 UTC 10532 DEBUG [verifyName] *.ashtavakra.org => ([^.]*\.|)?ashtavakra\.org - TcpConnectionImpl.cc:119
20220114 21:33:40.465663 UTC 10532 DEBUG [verifyAltName] Compare against hostname:  - TcpConnectionImpl.cc:175
20220114 21:33:40.465677 UTC 10532 ERROR Domain validation failed - TcpConnectionImpl.cc:1750
20220114 21:33:40.465683 UTC 10532 ERROR SSL certificate validation failed. - TcpConnectionImpl.cc:1769
```

**Comment by rbugajewski** [comment]
Closed due to inactivity.

**Comment by shivshankardayal** [comment]
This code used to work and after certain patches to Trantor it stopped working. This is a simple case of lack of regression tests. Also, I do not understand why it was not investigated by the author(s). I could have provided the link to source itself for debugging help. Anyway, since it is closed for no fault of mine I think it is time to move on from Drogon and its community.
