### ISSUE TITLE
[sugestion] runAfter, runEvery etc. could be overloaded to use chrono literals

### ISSUE THREAD

**Issue by moneroexamples** [an-tao/trantor#18]
I see in `trantor` there are lots of methods that take time duration as a parameters. A possible enhancement could be using chrono literals to write `1s`, `10min`. Example methods were such overloads would be useful are:

https://github.com/an-tao/trantor/blob/ef751cec815e457b735516d2dbc5b399edb333ec/trantor/net/EventLoop.h#L90-L97

**Comment by an-tao** [comment]
Sorry, just saw this issue, we have discussed similar issues in drogon and I will fix it. Thank you!

**Comment by moneroexamples** [comment]
No problem.

**Comment by an-tao** [comment]
@moneroexamples , It has been resolved. I forgot to make a PR...:-)
