### ISSUE TITLE
char[] need init

### ISSUE THREAD

**Issue by nqf** [an-tao/trantor#184]
Sometimes there is garbled code

https://github.com/an-tao/trantor/blob/master/trantor/net/InetAddress.cc#L188

**Comment by marty1885** [comment]
Thanks for making the issue. We are looking into it as there may be a deeper issue since inet_ntop always adds tailing 0s on success.

**Comment by nqf** [comment]
I don't know why, but I think it might be safer to initialize it because it sometimes prints random code in my application.
