### ISSUE TITLE
PIN thread per CPU for linux similar to seastar

### ISSUE THREAD

**Issue by viig99** [an-tao/trantor#199]
https://github.com/an-tao/trantor/blob/1af2c68ca216918073c336d5691c2316a56e0459/trantor/net/EventLoopThread.cc#L53

Wanted to understand if pinning the thread to a CPU id similar to seastar https://github.com/scylladb/seastar/blob/fcd46c13875b04510f8b38d66a82320cc1b393b8/include/seastar/core/posix.hh#L481 would lead to any improvement in performance, have you tried it before ? Is it even a good idea ?

**Comment by an-tao** [comment]
I've tested this technique and the performance dropped so I didn't use it, I'm not sure if I'm using it exactly, you could try it youself.
