### ISSUE TITLE
Issues compiling on Alpine Linux

### ISSUE THREAD

**Issue by sptrakesh** [an-tao/trantor#21]
I had to make a couple of modifications to InetAddress.cc to get trantor to compile on Alpine.  Not sure if they are good, since the drogon test suite crashes, but still you may want to take a look at the patch.

`diff --git a/trantor/net/InetAddress.cc b/trantor/net/InetAddress.cc
index db6339d..bf306a3 100755
--- a/trantor/net/InetAddress.cc
+++ b/trantor/net/InetAddress.cc
@@ -46,9 +46,9 @@ static const in_addr_t kInaddrLoopback = INADDR_LOOPBACK;
 using namespace trantor;
 
 #ifdef __linux__
-#if !(__GNUC_PREREQ(4, 6))
-#pragma GCC diagnostic ignored "-Winvalid-offsetof"
-#endif
+//#if !(__GNUC_PREREQ(4, 6))
+//#pragma GCC diagnostic ignored "-Winvalid-offsetof"
+//#endif
 #endif
 InetAddress::InetAddress(uint16_t port, bool loopbackOnly, bool ipv6)
     : _isIpV6(ipv6)
@@ -192,7 +192,7 @@ const uint32_t *InetAddress::ip6NetEndian() const
 {
 //assert(family() == AF_INET6);
 #ifdef __linux__
-    return _addr6.sin6_addr.__in6_u.__u6_addr32;
+    return _addr6.sin6_addr.__in6_union.__s6_addr32;
 #else
     return _addr6.sin6_addr.__u6_addr.__u6_addr32;
 #endif`

**Comment by an-tao** [comment]
@sptrakesh , Sorry for the late reply. Do you mind making a PR for this?
And there must be something wrong if the drogon test suite crashes, and I need more information to investigate.
I will test trantor and drogon on Alpine first.
Thank you.

**Comment by an-tao** [comment]
@sptrakesh , Fixed, thank you.
It seems that there is a problem with the drogon test suite on Alpine Linux, I will fix it.

**Comment by sptrakesh** [comment]
Thanks for fixing the issue and trying to fix the drogon issue on Alpine.

**Comment by an-tao** [comment]
Hi, @sptrakesh , After some investigation, I think the problem is the default stack size on Alpine Linux(See [this](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread_stack_size)).
I reduced the size of the temporary buffer in the SSLConnection class, and now the drogon test suite works fine.
You could check the new code to confirm it and thank you again!

**Comment by sptrakesh** [comment]
Thanks for the quick fix and the pointer to the stack size limitation with musl.  I verified that I can use drogon on alpine now.
