### ISSUE TITLE
Error on compiling OpenSSLProvider.cc

### ISSUE THREAD

**Issue by KambizAsadzadeh** [an-tao/trantor#245]
Hi, I get the following error at compile time in the new version.

**Host information:**
OpenSSL version: 3.1.0
OS version: macOS 13.2.1
Arch: M1 Arm64

-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found OpenSSL: /opt/homebrew/Cellar/openssl@3/3.1.0/lib/libcrypto.dylib (found version "3.1.0")  
-- Trantor using SSL library: OpenSSL
-- Found c-ares: /opt/homebrew/include  
-- c-ares found!
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Doxygen: /opt/homebrew/bin/doxygen (found version "1.9.6") found components: doxygen dot missing components: dia
-- Configuring done (1.1s)
-- Generating done (0.0s)

build % make
[  3%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/AsyncFileLogger.cc.o
[  6%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/ConcurrentTaskQueue.cc.o
[ 10%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Date.cc.o
[ 13%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/LogStream.cc.o
[ 16%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Logger.cc.o
[ 20%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/MsgBuffer.cc.o
[ 23%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/SerialTaskQueue.cc.o
[ 26%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/TimingWheel.cc.o
[ 30%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Utilities.cc.o
[ 33%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoop.cc.o
[ 36%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoopThread.cc.o
[ 40%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoopThreadPool.cc.o
[ 43%] Building CXX object CMakeFiles/trantor.dir/trantor/net/InetAddress.cc.o
[ 46%] Building CXX object CMakeFiles/trantor.dir/trantor/net/TcpClient.cc.o
[ 50%] Building CXX object CMakeFiles/trantor.dir/trantor/net/TcpServer.cc.o
[ 53%] Building CXX object CMakeFiles/trantor.dir/trantor/net/Channel.cc.o
[ 56%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Acceptor.cc.o
[ 60%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Connector.cc.o
[ 63%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Poller.cc.o
[ 66%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Socket.cc.o
[ 70%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/TcpConnectionImpl.cc.o
[ 73%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Timer.cc.o
[ 76%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/TimerQueue.cc.o
[ 80%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/EpollPoller.cc.o
[ 83%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/KQueue.cc.o
[ 86%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/PollPoller.cc.o
[ 90%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/tlsprovider/OpenSSLProvider.cc.o
/Users/user/drogon/trantor/trantor/net/inner/tlsprovider/OpenSSLProvider.cc:522:18: error: 'recvData' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual void recvData(MsgBuffer *buffer)
                 ^
/Users/user/drogon/trantor/trantor/net/inner/TLSProvider.h:35:18: note: overridden virtual function is here
    virtual void recvData(MsgBuffer* buffer) = 0;
                 ^
/Users/user/drogon/trantor/trantor/net/inner/tlsprovider/OpenSSLProvider.cc:562:21: error: 'sendData' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual ssize_t sendData(const char *data, size_t len)
                    ^
/Users/user/drogon/trantor/trantor/net/inner/TLSProvider.h:40:21: note: overridden virtual function is here
    virtual ssize_t sendData(const char* ptr, size_t size) = 0;
                    ^
2 errors generated.
make[2]: *** [CMakeFiles/trantor.dir/trantor/net/inner/tlsprovider/OpenSSLProvider.cc.o] Error 1
make[1]: *** [CMakeFiles/trantor.dir/all] Error 2
make: *** [all] Error 2

**Comment by marty1885** [comment]
Hi, thanks for reporting this. We merged a big TLS refactor. This among other issues should be fixed with a pending PR https://github.com/an-tao/trantor/pull/244

**Comment by marty1885** [comment]
@KambizAsadzadeh We merged several fixes. Cay you try again and let us know if it fixed the problem on your side?

**Comment by KambizAsadzadeh** [comment]
> 
Hi again,
Yes, of course, but there are still problems.

```
build % make -j

[  6%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Date.cc.o
[  6%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/AsyncFileLogger.cc.o
[ 10%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/ConcurrentTaskQueue.cc.o
[ 13%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Utilities.cc.o
[ 16%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/Logger.cc.o
[ 23%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoop.cc.o
[ 26%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoopThread.cc.o
[ 30%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/TimingWheel.cc.o
[ 33%] Building CXX object CMakeFiles/trantor.dir/trantor/net/Channel.cc.o
[ 36%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/MsgBuffer.cc.o
[ 36%] Building CXX object CMakeFiles/trantor.dir/trantor/net/EventLoopThreadPool.cc.o
[ 40%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/LogStream.cc.o
[ 43%] Building CXX object CMakeFiles/trantor.dir/trantor/net/TcpClient.cc.o
[ 46%] Building CXX object CMakeFiles/trantor.dir/trantor/net/InetAddress.cc.o
[ 50%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/SerialTaskQueue.cc.o
[ 53%] Building CXX object CMakeFiles/trantor.dir/trantor/net/TcpServer.cc.o
[ 56%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Acceptor.cc.o
[ 60%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Connector.cc.o
[ 63%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Poller.cc.o
[ 66%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Socket.cc.o
[ 70%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/TcpConnectionImpl.cc.o
[ 73%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/Timer.cc.o
[ 80%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/PollPoller.cc.o
[ 80%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/EpollPoller.cc.o
[ 83%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/TimerQueue.cc.o
[ 86%] Building CXX object CMakeFiles/trantor.dir/trantor/utils/crypto/openssl.cc.o
[ 90%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/tlsprovider/OpenSSLProvider.cc.o
[ 93%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/poller/KQueue.cc.o
[ 96%] Building CXX object CMakeFiles/trantor.dir/trantor/net/inner/AresResolver.cc.o
/Users/user/trantor/trantor/net/inner/tlsprovider/OpenSSLProvider.cc:570:21: error: 'sendData' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual ssize_t sendData(const char *data, size_t len)
                    ^
/Users/user/trantor/trantor/net/inner/TLSProvider.h:40:21: note: overridden virtual function is here
    virtual ssize_t sendData(const char* ptr, size_t size) = 0;
                    ^
1 error generated.
make[2]: *** [CMakeFiles/trantor.dir/trantor/net/inner/tlsprovider/OpenSSLProvider.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/trantor.dir/all] Error 2
make: *** [all] Error 2
```

Go to this line: https://github.com/an-tao/trantor/blob/1b0cb932aaa67e02ca1dbddf19e7d76309803e6c/trantor/net/inner/tlsprovider/OpenSSLProvider.cc#L570

We have virtual function ```sendData``` but is not marked 'override' in implement section!
I did it manually and it solved the problem.

So change it from 

```
virtual ssize_t sendData(const char *data, size_t len)
```

to 

```
virtual ssize_t sendData(const char *data, size_t len) override
```

The problem will be solved.
