### ISSUE TITLE
consider adding TCP_KEEPCNT， TCP_KEEPIDLE，TCP_KEEPINTVL settings from environment variable?

### ISSUE THREAD

**Issue by nqf** [an-tao/trantor#252]
Sometimes we need to set these three values， But we are unable to modify the system configuration， Currently, the trantor does not provide an interface to set it up
```
if(const char* env_p = std::getenv("TRANTOR_TCP_KEEPCNT")) {
    int optval = std::atoi(env_p)
    setsockopt(sockfd, SOL_TCP, TCP_KEEPCNT, &optval, optlen);
    // setsockopt(sockfd, SOL_TCP, TCP_KEEPIDLE, &optval, optlen);
    // setsockopt(sockfd, SOL_TCP, TCP_KEEPINTVL, &optval, optlen);
}
```

**Comment by nqf** [comment]
@an-tao  不考虑增加这个设置吗

**Comment by an-tao** [comment]
I prefer to add getFd() method to the TcpConnection class. what do you think?

**Comment by nqf** [comment]
> I prefer to add getFd() method to the TcpConnection class. what do you think?

我最终目的是期望可以在drogon中httpclient设置它，有办法在drogon中设置它吗

**Comment by an-tao** [comment]
httpclient要增加API处理getFd拿到的描述符

**Comment by nqf** [comment]
> httpclient要增加API处理getFd拿到的描述符

最好是可以提供一些回调 或者 构造参数之类的
```
auto http_client_ptr = drogon::HttpClient::newHttpClient();
http_client_ptr->setsockopt([](int fd) {
    // 
});
```
