### ISSUE TITLE
Missing headers for MinGW in `trantor/utils/AsyncFileLogger.cc`

### ISSUE THREAD

**Issue by HolyBlackCat** [an-tao/trantor#268]
The file `trantor/utils/AsyncFileLogger.cc` doesn't build for me when using MSYS2 UCRT64 Clang.

It needs `#include <dirent.h>` and `#include <sys/stat.h>`, which are disabled by `#ifndef _WIN32`.

**Comment by marty1885** [comment]
@HolyBlackCat Which compiler are you using? I'll try replicating this.

**Comment by HolyBlackCat** [comment]
@marty1885 Clang from MSYS2 UCRT64. You can follow [this installation guide](https://stackoverflow.com/q/30069830/2752075), then run `pacman -S mingw-w64-ucrt-x86_64-clang` to install Clang.

**Comment by marty1885** [comment]
@HolyBlackCat We merged a fix. Work on my MSYS UCRT installation. Can you try again?
