### ISSUE TITLE
drogon和这个项目能不能建个微信/QQ群？

### ISSUE THREAD

**Issue by funcproc** [an-tao/trantor#50]
个人很欣赏作者对muduo的改造，粗略看一下，去掉gcc的方言，去掉boost的各种依赖，重新引入C++17/14的promise的，重写TimerWheel，引入lambda，支持ssl，支持kqueue……，能不能建个微信/QQ群

**Comment by an-tao** [comment]
![301566744539_ pic](https://user-images.githubusercontent.com/21002501/63651727-9e7e4380-c78a-11e9-8bda-6b4fc728950f.jpg)
有一个，欢迎加入！您总结的很全面：）

**Comment by PharrellWANG** [comment]
二维码expire了，可以有个新二维码吗
